/**
 * 离线补全 en-US：不覆盖已有英文，仅翻译仍含中文的占位值。
 * 适合外网 Google 不可用 / 有道限流时使用。
 *
 * Usage:
 *   node scripts/i18n-offline-en.mjs --check
 *   node scripts/i18n-offline-en.mjs
 */

import fs from 'fs'
import path from 'path'
import { loadLocale as load, saveLocale as save, isMetaKey } from './locale-io.mjs'
import { getContext } from './context.mjs'

const CN_RE = /[\u4e00-\u9fff]/

function looksChinese(text) {
    return CN_RE.test(String(text || ''))
}

function isAlreadyEnglish(key, current) {
    if (current == null || current === '') return false
    if (current === key) return false
    if (!looksChinese(current)) return true
    return false
}

/** 领域词表（长词优先替换） */
const TERMS = {
    "沥青混合料理论最大相对密度试验检测记录表": 'Asphalt mixture theoretical max relative density test record',
    "粗集料及集料混合料的筛分试验检测记录表": 'Coarse aggregate & mixture sieve test record',
    "粗集料密度及吸水率试验检测记录表": 'Coarse aggregate density & water absorption test record',
    "粗集料试验检测报告": 'Coarse aggregate test report',
    "混合料理论最大相对密度": 'Mixture theoretical max relative density',
    "合成矿料的吸水率": 'Combined mineral aggregate water absorption',
    "纤维质量占矿料总质量百分比": 'Fiber mass % of total mineral aggregate',
    "平均累计筛余百分率": 'Avg cumulative retained %',
    "平均质量通过百分率": 'Avg mass passing %',
    "分计筛余百分率": 'Partial retained %',
    "累计筛余百分率": 'Cumulative retained %',
    "针片状颗粒含量": 'Flaky & elongated particle content',
    "振实堆积密度": 'Vibrated bulk density',
    "捣实堆积密度": 'Tamped bulk density',
    "松散堆积状态试样与筒总质量": 'Loose bulk sample + cylinder total mass',
    "捣实堆积状态试样与筒总质量": 'Tamped bulk sample + cylinder total mass',
    "振实堆积状态试样与筒总质量": 'Vibrated bulk sample + cylinder total mass',
    "瓶充满试样与溶剂总质量": 'Bottle + sample + solvent total mass',
    "瓶充满溶剂质量": 'Bottle filled with solvent mass',
    "试样、水、瓶及玻璃片总质量": 'Sample + water + bottle + glass plate total mass',
    "水、瓶及玻璃片总质量": 'Water + bottle + glass plate total mass',
    "容器加试样加水的质量": 'Container + sample + water mass',
    '容器+试样+水的质量': 'Container + sample + water mass',
    '容器+试样': 'Container + sample',
    "未烘干的试样与容器总质量": 'Undried sample + container total mass',
    "烘干后的试样与容器总质量": 'Dried sample + container total mass',
    "试验后烘干试样质量": 'Post-test dried sample mass',
    "试验前烘干试样质量": 'Pre-test dried sample mass',
    "试验后筛上试样烘干质量": 'Post-test retained dried sample mass',
    "筛上试样质量": 'Retained sample mass',
    "干燥试样总量": 'Total dry sample mass',
    "干筛后总质量": 'Total mass after dry sieving',
    "扣除损耗后总量": 'Total after deducting loss',
    "筛上总量": 'Total retained mass',
    "容量瓶质量": 'Volumetric flask mass',
    "容量筒质量": 'Capacity cylinder mass',
    "容器水中质量": 'Container mass in water',
    "容器质量": 'Container mass',
    "装满水的容器质量": 'Water-filled container mass',
    "试样表干质量": 'SSD sample mass',
    "试样烘干质量": 'Oven-dried sample mass',
    "试样空气中质量": 'Sample mass in air',
    "瓶加试样质量": 'Bottle + sample mass',
    '瓶+试样质量': 'Bottle + sample mass',
    "三氯乙烯相对密度": 'Trichloroethylene relative density',
    "水的密度": 'Water density',
    "标定的容量筒容积": 'Calibrated cylinder volume',
    "允许的最大空隙": 'Allowed max gap',
    "法线方向最大空隙": 'Max gap along normal',
    "尺至对应最大空隙": 'Max gap to matching point',
    "模拟拉直尺长度": 'Simulated straightedge length',
    "钢尺检查尺长度": 'Steel ruler check length',
    "填补能量计长度": 'Filling energy meter length',
    "公称最大粒径": 'Nominal max particle size',
    "最大粒径": 'Max particle size',
    "颗粒粒径": 'Particle size',
    "集料质量配比": 'Aggregate mass ratio',
    "矿料配合比": 'Mineral aggregate mix ratio',
    "混合料试拌油石比": 'Trial mix asphalt-aggregate ratio',
    "混合料的油石比": 'Mixture asphalt-aggregate ratio',
    "油石比": 'Asphalt-aggregate ratio',
    "空隙率": 'Voids',
    "泥块含量": 'Clay lump content',
    "含水率指标": 'Moisture content index',
    "含水率": 'Moisture content',
    "达标率": 'Compliance rate',
    "合格率": 'Pass rate',
    "未达标率": 'Non-compliance rate',
    "变异系数": 'Coefficient of variation',
    "损耗率": 'Loss rate',
    "合同占比": 'Contract share',
    "理论损耗占比": 'Theoretical loss ratio',
    "上限": 'Upper limit',
    "下限": 'Lower limit',
    "平均值": 'Average',
    "本期计划供货数量": 'Planned supply qty this period',
    "分期计划总需求量": 'Phased plan total demand',
    "供货总数量": 'Total supply qty',
    "累计收料数量": 'Cumulative received qty',
    "合同签约总量": 'Contract signed total',
    "已供货总量": 'Total already supplied',
    "剩余可供货量": 'Remaining supplyable qty',
    "剩余库存": 'Remaining stock',
    "实盘数量": 'Physical count qty',
    "账面数量": 'Book qty',
    "不合格总量": 'Total nonconforming',
    "生产总量": 'Total production',
    "消耗量": 'Consumption',
    "材料密度": 'Material density',
    "库存预警数值": 'Stock warning value',
    "物资一级预警阈值": 'Material L1 warning threshold',
    "物资二级预警阈值": 'Material L2 warning threshold',
    "运输车载重": 'Transport vehicle load',
    "总重": 'Gross weight',
    "毛重": 'Gross weight',
    "皮重": 'Tare weight',
    "净重": 'Net weight',
    "扣重": 'Deducted weight',
    "重量": 'Weight',
    "单价": 'Unit price',
    "退款成功金额": 'Refunded amount',
    "退款失败金额": 'Failed refund amount',
    "退款中金额": 'Refunding amount',
    "累计退款金额": 'Cumulative refund amount',
    "标高差值": 'Elevation difference',
    "高程差值": 'Elevation difference',
    "地面高程": 'Ground elevation',
    "平滑高程": 'Smoothed elevation',
    "摊铺高程": 'Paving elevation',
    "压实高程": 'Compaction elevation',
    "压实计算高程": 'Calculated compaction elevation',
    "压实设计高程": 'Design compaction elevation',
    "原高程": 'Original elevation',
    "桩顶高程偏差": 'Pile top elevation deviation',
    "桩顶高程": 'Pile top elevation',
    "桩位偏差": 'Pile position deviation',
    "桩间距": 'Pile spacing',
    "桩直径": 'Pile diameter',
    "桩径": 'Pile diameter',
    "桩深": 'Pile depth',
    "平均高": 'Avg height',
    "最大高": 'Max height',
    "最小高": 'Min height',
    "平均厚度": 'Avg thickness',
    "最大厚度": 'Max thickness',
    "最小厚度": 'Min thickness',
    "结构层厚度": 'Structural layer thickness',
    "虚铺厚度": 'Loose paving thickness',
    "压实厚度": 'Compacted thickness',
    "摊铺厚": 'Paving thickness',
    "压实厚": 'Compaction thickness',
    "拓宽宽度": 'Widening width',
    "填方点数比例": 'Fill points ratio',
    "挖方点数比例": 'Cut points ratio',
    "填方最大深度": 'Max fill depth',
    "挖方最大深度": 'Max cut depth',
    "挖方平均深度": 'Avg cut depth',
    "填方": 'Fill',
    "挖方": 'Cut',
    "碾压遍数": 'Pass count',
    "碾压速度": 'Rolling speed',
    "碾压温度": 'Rolling temperature',
    "摊铺速度": 'Paving speed',
    "摊铺温度": 'Paving temperature',
    "温差分析": 'Temp difference analysis',
    "试验水温": 'Test water temperature',
    "集料温度": 'Aggregate temperature',
    "检校周期": 'Calibration cycle',
    "测量北": 'Survey North',
    "测量东": 'Survey East',
    "测量高": 'Survey Elev',
    "平板北": 'Tablet North',
    "平板东": 'Tablet East',
    "平板高": 'Tablet Elev',
    "发料单": 'Issue slip',
    "收料单": 'Receiving slip',
    "内转材料": 'Internal transfer material',
    '收/发料单': 'Receive/Issue slip',
    "明细": 'details',
    "磅单": 'weighbridge slip',
    "专用章图片": 'Official seal image',
    "透明背景": 'transparent background',
    "安全模式": 'Secure mode',
    "兼容模式": 'Compatible mode',
    "明文模式": 'Plaintext mode',
    "推荐": 'recommended',
    "热拌站": 'Hot-mix plant',
    "热门搜索": 'Hot searches',
    "任意时间段": 'Any time range',
    "日产值": 'Daily output value',
    "日期控件": 'Date control',
    "日志时间": 'Log time',
    "溶剂法": 'Solvent method',
    "软删除": 'Soft delete',
    "弱振": 'Low vibration',
    "复压": 'Intermediate rolling',
    "渠道状态": 'Channel status',
    "取消多选": 'Cancel multi-select',
    "取样人": 'Sampler',
    "去装修": 'Go decorate',
    "全匹配": 'Exact match',
    '全选/不全选': 'Select all / none',
    "权限标识": 'Permission key',
    "权限字符": 'Permission char',
    "权限": 'Permission',
    "确认密码": 'Confirm password',
    "确认修改": 'Confirm change',
    "确认": 'Confirm',
    "确定密码": 'Confirm password',
    "悍马": 'Hamm',
    "双钢轮": 'tandem roller',
    "真空法": 'vacuum method',
    "容量瓶法": 'volumetric flask method',
    "水洗法": 'washing method',
    "沥青混合料用": 'for asphalt mixture',
    "最佳油石比": 'optimum asphalt-aggregate ratio',
    "工作层级": 'Work layer',
    "层级越靠上数值越大": 'higher layer = larger value',
    "消息包为纯密文": 'message body is fully encrypted',
    "需要开发者加密和解密": 'developer must encrypt/decrypt',
    "安全系数高": 'higher security',
    "明文、密文将共存": 'plain & cipher coexist',
    "方便开发者调试和维护": 'easier for debug & maintenance',
    "不使用消息体加解密功能": 'no message body crypto',
    "安全系数较低": 'lower security',
    "只能输入小数点后两位": 'max 2 decimal places',
    "如外网地址需内链访问则以": 'for external URLs use',
    "开头": 'prefix',
    "访问的路由地址": 'Route path',
    "如": 'e.g.',
    "保存": 'Save',
    "获取菜单": 'Get menu',
    "获取": 'Get',
    "新增": 'Add',
    "编辑": 'Edit',
    "关闭": 'Close',
    "下载二维码": 'Download QR code',
    "查看级配": 'View gradation',
    "查看配合比": 'View mix ratio',
    "坐标偏移": 'Coordinate offset',
    "长度": 'Length',
    "配置": 'config',
    "请选择": 'Please select ',
    "条": '',
    "未处理": 'Pending',
    "处理中": 'Processing',
    "处理完成": 'Done',
    "请输入": 'Please enter ',
    "请选择": 'Please select ',
    "请添加": 'Please add ',
    "请填写": 'Please fill in ',
    "请先": 'Please ',
    "请再次": 'Please again ',
    "请至少": 'Please at least ',
    "请仔细": 'Please carefully ',
    "确定要": 'Confirm ',
    "确认": 'Confirm ',
    "拌合站": 'mixing plant',
    "磅房": 'weighbridge',
    "报告类型": 'report type',
    "报警级别": 'alarm level',
    "标段": 'section',
    "层级": 'layer',
    "车辆": 'vehicle',
    "成桩时间": 'pile completion time',
    "单据状态": 'document status',
    "道路幅": 'road carriageway',
    "登录页广告图": 'login ad image',
    "父级菜单": 'parent menu',
    "工艺类型": 'process type',
    "工艺": 'process',
    "工作组": 'work group',
    "功能室": 'utility room',
    "供应商名称": 'supplier name',
    "供应商": 'supplier',
    "关联磅房": 'linked weighbridge',
    "关联供货合同": 'linked supply contract',
    "关联供应商": 'linked supplier',
    "关联健": 'linked key',
    "关联类型": 'link type',
    "关联模型": 'linked model',
    "关联试验": 'linked test',
    "合同截止日期": 'contract end date',
    "合同生效日期": 'contract start date',
    "回复类型": 'reply type',
    "计划截止日期": 'plan end date',
    "计划开始日期": 'plan start date',
    "计量单位": 'unit of measure',
    "检测人": 'inspector',
    "角色": 'role',
    "结构层": 'structural layer',
    "结束日期": 'end date',
    "进场材料": 'incoming material',
    "进场时间": 'entry time',
    "开始日期": 'start date',
    "开始与结束时间": 'start and end time',
    "时分秒": 'h:m:s',
    "类型": 'type',
    "录入人": 'entered by',
    "年份": 'year',
    "盘点日期": 'inventory date',
    "判定依据": 'judgment basis',
    "配方标识": 'formula id',
    "配方": 'formula',
    "匹配方式": 'match mode',
    "启用状态": 'enabled status',
    "取样日期": 'sampling date',
    "删除字段": 'delete field',
    "商城": 'mall',
    "上传状态": 'upload status',
    "上级部门": 'parent dept',
    "上级类别": 'parent category',
    "上级类型": 'parent type',
    "上级": 'parent',
    "设备工艺": 'device process',
    "设备类型": 'device type',
    "设备状态": 'device status',
    "生产时间": 'production time',
    "施工层级": 'construction layer',
    "施工日期": 'construction date',
    "施工时间": 'construction time',
    "试验类型": 'test type',
    "试验名称": 'test name',
    "试验日期": 'test date',
    "试验室名称": 'lab name',
    "是否": 'whether',
    "摊铺": 'paving',
    "补单": 'supplementary order',
    "拓宽路面": 'road widening',
    "标准物质": 'reference material',
    "数据表": 'data table',
    "数据来自": 'data from',
    "数据": 'data',
    "水比": 'water ratio',
    "水泥比": 'cement ratio',
    "速度状态": 'speed status',
    "所属标段": 'section',
    "所属部门": 'department',
    "所属系统": 'system',
    "网站图标": 'site icon',
    "网站": 'website',
    "文章栏目": 'article column',
    "物资名称": 'material name',
    "样品分类": 'sample category',
    "样品类型": 'sample type',
    "样品状态": 'sample status',
    "预检时间": 'pre-check time',
    "状态": 'status',
    "组织架构": 'org structure',
    "组织": 'organization',
    "左右幅": 'left/right carriageway',
    "出厂编号": 'factory serial',
    "出场物料员": 'outbound material clerk',
    "创建时间": 'created at',
    "从事检测行业年限": 'years in testing',
    "存储空间名称": 'bucket name',
    "代表数量": 'representative qty',
    "单据类别": 'document category',
    "单据": 'document',
    "当前编号": 'current no.',
    "当前密码": 'current password',
    "地址": 'address',
    "电话": 'phone',
    "店铺": 'shop',
    "商城名称": 'mall name',
    "调整的金额": 'adjustment amount',
    "短信内容": 'SMS content',
    "短信签名": 'SMS signature',
    "分包单位责任人": 'subcontractor contact',
    "分类": 'category',
    "分组名称": 'group name',
    "分组": 'group',
    "负责人姓名": 'person in charge',
    "岗位编码": 'post code',
    "岗位名称": 'post name',
    "工程部位": 'work location',
    "用途": 'purpose',
    "工程名称": 'project name',
    "工艺名称": 'process name',
    "公众号名称": 'official account name',
    "功能室名称": 'utility room name',
    "供应商来源": 'supplier source',
    "关键词搜索": 'keyword search',
    "关键词": 'keyword',
    "关键字": 'keyword',
    "关联合同数量": 'linked contract qty',
    "关联名称": 'linked name',
    "关联系统": 'linked system',
    "关注公众号地址": 'follow-OA URL',
    "管理人": 'manager',
    "灌入量": 'pour volume',
    "规格型号": 'spec/model',
    "规格": 'spec',
    "规则名称": 'rule name',
    "合法的网址链接": 'valid URL',
    "合同编号": 'contract no.',
    "合同名称": 'contract name',
    "后报警": 'rear alarm',
    "回复内容": 'reply content',
    "级配数据": 'gradation data',
    "计划重量": 'planned weight',
    "技术参数": 'tech params',
    "驾驶员": 'driver',
    "检测单位": 'testing unit',
    "检测人员名称": 'inspector name',
    "简介": 'intro',
    "浇筑部位": 'pouring location',
    "结束桩号": 'end station',
    "结束桩": 'end stake',
    "进场物料员": 'inbound material clerk',
    "开始桩号": 'start station',
    "开始桩": 'start stake',
    "空间域名": 'bucket domain',
    "宽度": 'width',
    "来源单号": 'source doc no.',
    "栏目名称": 'column name',
    "联系电话": 'contact phone',
    "联系人": 'contact',
    "链接": 'link',
    "量程": 'range',
    "料仓名称": 'silo name',
    "料仓": 'silo',
    "录入时间": 'entry time',
    "路标识": 'road mark',
    "路宽": 'road width',
    "路由参数": 'route params',
    "路由地址": 'route path',
    "路由路径": 'route path',
    "密码": 'password',
    "模板": 'template',
    "模块名": 'module name',
    "昵称": 'nickname',
    "排序": 'sort',
    "配方编号": 'formula no.',
    "配方国标": 'formula national std',
    "配方名称": 'formula name',
    "配合比信息": 'mix ratio info',
    "偏移时间": 'offset time',
    "品牌": 'brand',
    "前报警": 'front alarm',
    "前台名称": 'frontend name',
    "强度": 'strength',
    "倾角": 'tilt angle',
    "倾斜度": 'inclination',
    "取样地点": 'sampling place',
    "确定密码": 'confirm password',
    "日期": 'date',
    "年月": 'year-month',
    "删除": 'delete',
    "正常": 'normal',
    "设备编号": 'device no.',
    "设备编码": 'device code',
    "设备参数": 'device params',
    "设备来源": 'device source',
    "设备类型相关": 'device-type related',
    "设备名称": 'device name',
    "设备型号": 'device model',
    "生产厂家": 'manufacturer',
    "施工": 'construction',
    "委托单位": 'client unit',
    "实际浏览量": 'actual views',
    "实验名称": 'experiment name',
    "视频名称": 'video name',
    "视频图片": 'video cover',
    "试验类型名": 'test type name',
    "是否合格": 'pass/fail',
    "是否上传": 'uploaded or not',
    "是否审批": 'approved or not',
    "是否显示": 'show or not',
    "数据快照": 'data snapshot',
    "数据名称": 'data name',
    "数据时间": 'data time',
    "数据值": 'data value',
    "数量": 'quantity',
    "所属项目": 'project',
    "拓宽结束桩号": 'widening end station',
    "拓宽开始桩号": 'widening start station',
    "提管速度": 'pipe lift speed',
    "提前预警天数": 'advance warning days',
    "体积": 'volume',
    "图片路径": 'image path',
    "退款单号": 'refund no.',
    "外键": 'foreign key',
    "完整的": 'full ',
    "网站名称": 'site name',
    "微信支付商户号": 'WeChat Pay merchant id',
    "微信支付商户": 'WeChat Pay merchant ',
    "微信支付证书密钥": 'WeChat Pay cert key',
    "微信支付证书": 'WeChat Pay cert',
    "唯一标识": 'unique id',
    "文件描述": 'file description',
    "文件所在目录": 'file directory',
    "文章标题": 'article title',
    "文章分类": 'article category',
    "文章简介": 'article intro',
    "文章内容": 'article content',
    "文章图片": 'article image',
    "文章摘要": 'article summary',
    "无报警": 'no alarm',
    "物料名称": 'material name',
    "物料": 'material',
    "物资类别": 'material category',
    "显示名称": 'display name',
    "项目部责任人": 'project dept owner',
    "项目说明": 'project note',
    "项目": 'project',
    "小程序名称": 'mini program name',
    "校差": 'calibration error',
    "新的密码": 'new password',
    "型号": 'model',
    "姓名": 'name',
    "虚拟浏览量": 'virtual views',
    "验收情况": 'acceptance status',
    "验收人": 'acceptor',
    "样品编号": 'sample no.',
    "样品分类名": 'sample category name',
    "样品描述": 'sample description',
    "样品名称": 'sample name',
    "业务类别": 'business category',
    "页面标题": 'page title',
    "用户名": 'username',
    "用户信息": 'user info',
    "用户账号": 'user account',
    "手机号": 'mobile',
    "预警状态": 'warning status',
    "黄色预警": 'yellow warning',
    "红色预警": 'red warning',
    "原材料": 'raw material',
    "原始配方标识": 'original formula id',
    "原始匹配后的数据": 'matched raw data',
    "原始": 'original ',
    "原因": 'reason',
    "月份": 'month',
    "责任单位": 'responsible unit',
    "站点名称": 'station name',
    "站点": 'station',
    "账号": 'account',
    "正整数": 'positive integer',
    "支付宝公钥": 'Alipay public key',
    "支付宝应用私钥": 'Alipay app private key',
    "支付宝应用": 'Alipay app ',
    "执行比例": 'execution ratio',
    "专业": 'specialty',
    "字典类型": 'dict type',
    "字典名称": 'dict name',
    "总量数据": 'total data',
    "租户": 'tenant',
    "组件地址": 'component path',
    "组件路径": 'component path',
    "钻进速度": 'drilling speed',
    "最低充值金额": 'min top-up amount',
    "最后登录": 'last login ',
    "最后时间": 'last time',
    "最后修改人": 'last modified by',
    "最后修改时间": 'last modified at',
    "左报警": 'left alarm',
    "作者名称": 'author name',
    "作者": 'author',
    "坐标偏移量": 'coordinate offset',
    "盖章后再审批": 'seal then approve',
    "监理意见": 'supervisor opinion',
    "数据后再提交": 'data before submit',
    "应用": 'app ',
    "绘制围栏区域": 'draw fence area',
    "加载扩建侧路径文件": 'load widening-side path file',
    "加载路面点云文件": 'load road point-cloud file',
    "上传": 'upload ',
    "文件": 'file',
    "选择站点": 'select a station',
    "订阅类型": 'subscription type',
    "后再提交": ' before submit',
    "示例": 'e.g.',
    "主线": 'mainline',
    "砟道": 'ballast track',
    "关": 'off',
    "开启": 'on',
    "是": 'yes',
    "否": 'no',
    "次数": 'count',
    "温度": 'temperature',
    "厚度": 'thickness',
    "级配上限": 'gradation upper',
    "级配下限": 'gradation lower',
    "合成级配": 'combined gradation',
    "轴缩减": '-axis reduce: ',
    "轴放大": '-axis enlarge: ',
    "权限似乎出了点问题": 'Permission seems wrong',
    "确定离开此页面": 'Leave this page',
    "系统可能不会保存您所做的更改": 'changes may not be saved',
    "确定要关闭么": 'Close now',
    "归档": 'archive',
    "删除这个围栏吗": 'delete this fence',
    "同步表结构": 'sync table schema',
    "清除系统缓存": 'clear system cache',
    "退款": 'refund',
    "重新退款": 'retry refund',
    "推送模块": 'push module',
    "域名拼写是否正确": 'domain spelling is correct',
    "或联系平台管理员处理": 'or contact the admin',
    "粉丝在公众号发送内容时": 'when followers send messages',
    "通过关键词可触发关键词回复": 'keywords can trigger auto-replies',
    "同时可启用多个关键词回复": 'multiple keyword replies can be enabled',
    "有多条关键词匹配时优选选择排序靠前的一条": 'if multiple match, prefer the highest-sorted one',
    "温馨提示": 'Tip',
    "控制器": 'controller',
    "逻辑": 'logic',
    "模型": 'model',
    "生成文件描述为": 'generated file desc is',
    "填写": 'enter ',
    "例": 'e.g.',
    "千克": 'kg',
    "吨": 't',
    "元": 'CNY',
    "月": 'month',
    "遍": 'passes',
    "摄氏度": '°C'
}

const PREFIX_RULES = [
    [/^请输入/, 'Please enter '],
    [/^请选择/, 'Please select '],
    [/^请添加/, 'Please add '],
    [/^请填写/, 'Please fill in '],
    [/^请先/, 'Please '],
    [/^请再次/, 'Please re-'],
    [/^请至少/, 'Please at least '],
    [/^请仔细/, 'Please carefully '],
    [/^确定要/, 'Confirm to '],
    [/^确认/, 'Confirm ']
]

function applyTerms(text) {
    let out = text
    const keys = Object.keys(TERMS).sort((a, b) => b.length - a.length)
    for (const k of keys) {
        if (out.includes(k)) out = out.split(k).join(TERMS[k])
    }
    return out
}

function translateOffline(key) {
    // 兜底整句表优先
    const FALLBACK = {
        日期: 'Date',
        权限: 'Permission',
        确认: 'Confirm',
        取样人: 'Sampler',
        热拌站: 'Hot-mix plant',
        热门搜索: 'Hot searches',
        软删除: 'Soft delete',
        弱振: 'Low vibration',
        溶剂法: 'Solvent method',
        渠道状态: 'Channel status',
        取消多选: 'Cancel multi-select',
        去装修: 'Go decorate',
        全匹配: 'Exact match',
        日产值: 'Daily output value',
        任意时间段: 'Any time range',
        '保存=>': 'Save =>',
        '获取=>': 'Fetch =>',
        '获取菜单=>': 'Fetch menu =>',
        'x轴缩减：': 'X-axis reduce:',
        'y轴放大：': 'Y-axis enlarge:',
        '<br/>长度：': '<br/>Length:',
        '{a} <br/>{b}: {c}条 ({d}%)': '{a} <br/>{b}: {c} ({d}%)',
        '{b}<br/>{c} 条 · {d}%': '{b}<br/>{c} · {d}%',
        '`${popupTitle}配置`': '`${popupTitle} config`',
        '`请选择` + item.name': '`Please select ` + item.name',
        '`坐标偏移`': '`Coordinate offset`',
        "item !== '摊铺'": "item !== 'Paving'",
        '粤A12345': 'YueA12345',
        '0.075mm筛下量(g)': 'Mass under 0.075mm sieve (g)',
        '0.075mm通过率(%)': '0.075mm passing rate (%)',
        '请输入微信支付商户API密钥': 'Please enter WeChat Pay merchant API key',
        '请输入准确度': 'Please enter accuracy',
        '请输入json字符串 传递过来': 'Please enter the JSON string to pass',
        '请输入PC端网站标题': 'Please enter PC site title',
        '请输入PC端网站关键词': 'Please enter PC site keywords',
        '请输入PC端网站描述': 'Please enter PC site description',
        '请选择是否为标准物质': 'Please select whether it is a reference material',
        '请选择PC端网站图标': 'Please select PC site icon',
        '请选择PC端LOGO': 'Please select PC LOGO',
        '请再次输入密码': 'Please re-enter password',
        '请至少选择一种推送模块': 'Please select at least one push module',
        '请仔细检查域名拼写是否正确或联系平台管理员处理':
            'Please carefully check the domain spelling or contact the platform admin',
        '确认修改': 'Confirm changes',
        '日报.pdf': 'Daily report.pdf',
        '日生产数据.csv': 'Daily production data.csv',
        '日生产数据.pdf': 'Daily production data.pdf',
        '日生产数据.xlsx': 'Daily production data.xlsx',
        '试验后2.36mm筛上试样烘干质量(g)': 'Post-test 2.36mm retained dried sample mass (g)',
        '速度(km/h)': 'Speed (km/h)',
        '损耗(g)': 'Loss (g)'
    }
    if (FALLBACK[key]) return FALLBACK[key]

    // 明显是代码/表达式：尽量只替换汉字片段
    if (/[=<>`]|\|\||&&|\?\.|item\.|daily\.|legend|cell\./.test(key) && looksChinese(key)) {
        return applyTerms(key)
    }

    let text = key
    let prefix = ''
    for (const [re, en] of PREFIX_RULES) {
        if (re.test(text)) {
            prefix = en
            text = text.replace(re, '')
            break
        }
    }

    text = applyTerms(text)
    text = text
        .replace(/（/g, '(')
        .replace(/）/g, ')')
        .replace(/：/g, ': ')
        .replace(/；/g, '; ')
        .replace(/，/g, ', ')
        .replace(/。/g, '. ')
        .replace(/、/g, ', ')
        .replace(/～/g, '~')
        .replace(/吗\??/g, '?')
        .replace(/么\??/g, '?')
        .replace(/？/g, '?')
        .replace(/\s{2,}/g, ' ')
        .trim()

    let result = (prefix + text).replace(/\s{2,}/g, ' ').trim()
    if (looksChinese(result)) result = applyTerms(result)
    if (looksChinese(result) && FALLBACK[text]) return prefix + FALLBACK[text]
    return result || key
}

export function runOfflineEn(argv = []) {
    const checkOnly = argv.includes('--check')
    const { sourceLocale, reportsDir, root } = getContext()
    const zh = load(sourceLocale)
    const en = load('en-US')
    let kept = 0
    let filled = 0
    const leftover = []

    for (const key of Object.keys(zh)) {
        if (isMetaKey(key)) continue
        const current = en[key]
        if (isAlreadyEnglish(key, current)) {
            kept++
            continue
        }
        const translated = translateOffline(key)
        if (!translated || translated === key || looksChinese(translated)) {
            leftover.push(key)
            continue
        }
        if (!checkOnly) {
            en[key] = translated
        }
        filled++
    }

    console.log(`[i18n:offline-en] already English (KEEP): ${kept}`)
    console.log(`[i18n:offline-en] would/filled: ${filled}`)
    console.log(`[i18n:offline-en] still chinese-ish: ${leftover.length}`)

    fs.mkdirSync(reportsDir, { recursive: true })
    const leftoverPath = path.join(reportsDir, 'i18n-offline-leftover.json')
    fs.writeFileSync(leftoverPath, JSON.stringify([...new Set(leftover)], null, 2), 'utf8')
    console.log(`[i18n:offline-en] leftover -> ${path.relative(root, leftoverPath)}`)

    if (checkOnly) {
        console.log('[i18n:offline-en] check-only, no write')
        return
    }

    save('en-US', en)
    console.log('[i18n:offline-en] wrote en-US.json')
}
